### PR TITLE
README.md shorter working + inline comments when possible.

### PR DESCRIPTION
**Pull request by hugolpz**
Concise comments approach when possible.
Inline comments approach when possible.
Aligned en, cn, tw.
Added the `HTML attribute lang`, which is a core part of your system for browsers.
Switched to example 漢語 -> 汉语.

### CODE REVIEW

**Review by sgalal — APPROVED** [review]

**Comment by sgalal** [comment]
Thanks! Would you please modify the translations (`README-zh-TW.md` and `README-zh-CN.md`) as well?

**Comment by hugolpz** [comment]
I will do my best but I'am not a native Chinese speaker.

**Comment by hugolpz** [comment]
Changed listed above.

**Review by sgalal — APPROVED** [review]
Thank you!

**Comment by hugolpz** [comment]
few minor changes coming.

**Pull request merged**
